---
- name: Installer Kea DHCP et Dépendances
  apt:
    name:
      - kea-dhcp4-server
      - kea-admin
      - kea-common
    state: present
    update_cache: yes

- name: Créer le répertoire de logs
  file:
    path: /var/log/kea
    state: directory
    owner: _kea
    group: _kea
    mode: '0755'

- name: Déployer la configuration Kea HA
  template:
    src: kea-dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
    owner: root
    group: _kea
    mode: '0640'
    validate: 'kea-dhcp4 -t %s'
  notify: restart kea

- name: Démarrer Kea DHCP v4
  systemd:
    name: kea-dhcp4-server
    state: started
    enabled: yes