---
- name: Installer Kea DHCP
  apt:
    name: kea-dhcp4-server
    state: present
    update_cache: yes
    cache_valid_time: 3600


- name: Créer le répertoire de logs
  file:
    path: /var/log/kea
    state: directory
    owner: _kea
    group: _kea
    mode: '0750'

- name: Déployer la configuration
  template:
    src: kea-dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
    owner: root
    group: _kea
    mode: '0640'
    validate: 'kea-dhcp4 -t %s'
  notify: restart kea

- name: Démarrer le service
  systemd:
    name: kea-dhcp4-server
    state: started
    enabled: yes