---
- name: Installer les dépendances systèmes de base
  apt:
    name:
      - unzip
      - tar
      - curl
      - wget
      - acl # Nécessaire pour Ansible 'become' user
    state: present
    update_cache: yes

- name: Configure NTP (Chrony)
  import_tasks: ntp.yml

- name: Configure Log Shipping (Promtail)
  import_tasks: logging.yml

- name: Configure Backup Client (PBS)
  import_tasks: backup.yml
