---
kea_interfaces: 
  - "eth0"
kea_dns_servers: "10.0.10.11, 10.0.10.12"
kea_valid_lifetime: 4000
kea_lease_file: "/var/lib/kea/kea-leases4.csv"
kea_log_file: "/var/log/kea/kea-dhcp4.log"
kea_log_severity: "INFO"

kea_subnets:
  - id: 10
    name: "ZONE INFRA - VLAN 10"
    subnet: "10.0.10.0/24"
    pool_start: "10.0.10.100"
    pool_end: "10.0.10.200"
    gateway: "10.0.10.1"
    use_global_dns: true
    reservations: []

  - id: 20
    name: "ZONE MGMT - VLAN 20"
    subnet: "10.0.20.0/24"
    pool_start: "10.0.20.100"
    pool_end: "10.0.20.200"
    gateway: "10.0.20.1"
    use_global_dns: true
    reservations: []

  - id: 30
    name: "ZONE APP - VLAN 30"
    subnet: "10.0.30.0/24"
    pool_start: "10.0.30.100"
    pool_end: "10.0.30.200"
    gateway: "10.0.30.1"
    use_global_dns: true
    reservations: []

  - id: 40
    name: "ZONE DATA - VLAN 40 (STATIQUE SEULEMENT)"
    subnet: "10.0.40.0/24"
    pool_start: ""
    pool_end: ""
    gateway: "10.0.40.1"
    use_global_dns: false
    reservations: []
