# 1. Configuration commune Ã  toutes les machines
- hosts: all
  become: yes
  roles:
    - common

# 2. Configuration database
- hosts: databases
  become: yes
  roles:
    - database

# 3. Configuration Kea DHCP Servers
- name: Configuration de l'infrastructure DHCP
  hosts: dhcp_servers
  become: yes
  roles:
    - kea_dhcp