---
- name: Créer le dossier de configuration RKE2
  file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: Créer le dossier des manifestes de pods statiques RKE2
  file:
    path: /var/lib/rancher/rke2/server/manifests
    state: directory
    recurse: yes

# --- KUBE-VIP (Masters Uniquement) ---
- name: Déployer le manifeste Kube-VIP
  template:
    src: kube-vip.yaml.j2
    dest: /var/lib/rancher/rke2/server/manifests/kube-vip.yaml
  when: "'master' in group_names"

# --- CONFIGURATION RKE2 ---
- name: Configurer RKE2 (Master)
  template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
  when: "'master' in group_names"

- name: Configurer RKE2 (Worker)
  copy:
    dest: /etc/rancher/rke2/config.yaml
    content: |
      server: https://{{ rke2_vip }}:9345
      token: {{ rke2_token }}
  when: "'worker' in group_names"

# --- INSTALLATION ---
- name: Installer RKE2
  shell: curl -sfL https://get.rke2.io | sh -
  args:
    creates: /usr/local/bin/rke2
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2_version }}"
    # Définit le type: server (master) ou agent (worker)
    INSTALL_RKE2_TYPE: "{{ 'server' if 'master' in group_names else 'agent' }}"

# --- GESTION DU SERVICE ---

# Master 1 (Bootstrap)
- name: Démarrer RKE2 Server (Bootstrap)
  service:
    name: rke2-server
    state: started
    enabled: yes
  when: 
    - "'master' in group_names"
    - inventory_hostname == groups['master'][0]

- name: Attendre le serveur API
  wait_for:
    host: "{{ hostvars[groups['master'][0]].ansible_host }}"
    port: 6443
    delay: 10
    timeout: 300
  when: 
    - "'master' in group_names"
    - inventory_hostname != groups['master'][0]

# Autres Masters (Rejoindre)
- name: Démarrer RKE2 Server (Rejoindre)
  service:
    name: rke2-server
    state: started
    enabled: yes
  when: 
    - "'master' in group_names"
    - inventory_hostname != groups['master'][0]

# Workers
- name: Démarrer RKE2 Agent
  service:
    name: rke2-agent
    state: started
    enabled: yes
  when: "'worker' in group_names"
